# Generated by Django 5.1.3 on 2024-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_location',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
